"""Adiciona campo admin em Usuario

Revision ID: 1bbc9f55a539
Revises: cd29cbe8b2af
Create Date: 2026-02-13 09:58:38.534959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbc9f55a539'
down_revision = 'cd29cbe8b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
